package com.huibao.esb.insureservice.client.tiananquery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.4
 * 2015-04-13T15:05:57.824+08:00
 * Generated source version: 2.4.4
 * 
 */
@WebService(targetNamespace = "http://netSale.inters.service.interact.esb.sinosoft.com/", name = "NoPolicyQueryDetail")
@XmlSeeAlso({ObjectFactory.class})
public interface NoPolicyQueryDetail {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "doPolicyQueryDetail", targetNamespace = "http://netSale.inters.service.interact.esb.sinosoft.com/", className = "com.huibao.esb.insureservice.client.tiananquery.DoPolicyQueryDetail")
    @WebMethod
    @ResponseWrapper(localName = "doPolicyQueryDetailResponse", targetNamespace = "http://netSale.inters.service.interact.esb.sinosoft.com/", className = "com.huibao.esb.insureservice.client.tiananquery.DoPolicyQueryDetailResponse")
    public java.lang.String doPolicyQueryDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
