package com.huibao.esb.insureservice.client.tiananquery;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.4
 * 2015-04-13T15:05:57.882+08:00
 * Generated source version: 2.4.4
 * 
 */
@WebServiceClient(name = "NoPolicyQueryDetailService", 
                  wsdlLocation = "http://180.168.131.15/netsalesService/doPolicyQueryDetail?wsdl",
                  targetNamespace = "http://netSale.inters.service.interact.esb.sinosoft.com/") 
public class NoPolicyQueryDetailService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://netSale.inters.service.interact.esb.sinosoft.com/", "NoPolicyQueryDetailService");
    public final static QName NoPolicyQueryDetailPort = new QName("http://netSale.inters.service.interact.esb.sinosoft.com/", "NoPolicyQueryDetailPort");
    static {
        URL url = null;
        try {
            url = new URL("http://180.168.131.15/netsalesService/doPolicyQueryDetail?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NoPolicyQueryDetailService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://180.168.131.15/netsalesService/doPolicyQueryDetail?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NoPolicyQueryDetailService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NoPolicyQueryDetailService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NoPolicyQueryDetailService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns NoPolicyQueryDetail
     */
    @WebEndpoint(name = "NoPolicyQueryDetailPort")
    public NoPolicyQueryDetail getNoPolicyQueryDetailPort() {
        return super.getPort(NoPolicyQueryDetailPort, NoPolicyQueryDetail.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NoPolicyQueryDetail
     */
    @WebEndpoint(name = "NoPolicyQueryDetailPort")
    public NoPolicyQueryDetail getNoPolicyQueryDetailPort(WebServiceFeature... features) {
        return super.getPort(NoPolicyQueryDetailPort, NoPolicyQueryDetail.class, features);
    }

}
