package com.huibao.esb.insureservice.client.tianan;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.4
 * 2015-03-25T14:51:14.568+08:00
 * Generated source version: 2.4.4
 * 
 */
@WebServiceClient(name = "NoCarProposalSaveService", 
                  wsdlLocation = "http://180.168.131.15/netsalesServicedev/doCarProposalSave?wsdl",
                  targetNamespace = "http://netSale.inters.service.interact.esb.sinosoft.com/") 
public class NoCarProposalSaveService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://netSale.inters.service.interact.esb.sinosoft.com/", "NoCarProposalSaveService");
    public final static QName NoCarProposalSavePort = new QName("http://netSale.inters.service.interact.esb.sinosoft.com/", "NoCarProposalSavePort");
    static {
        URL url = null;
        try {
            url = new URL("http://180.168.131.15/netsalesServicedev/doCarProposalSave?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NoCarProposalSaveService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://180.168.131.15/netsalesServicedev/doCarProposalSave?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NoCarProposalSaveService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NoCarProposalSaveService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NoCarProposalSaveService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns NoCarProposalSave
     */
    @WebEndpoint(name = "NoCarProposalSavePort")
    public NoCarProposalSave getNoCarProposalSavePort() {
        return super.getPort(NoCarProposalSavePort, NoCarProposalSave.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NoCarProposalSave
     */
    @WebEndpoint(name = "NoCarProposalSavePort")
    public NoCarProposalSave getNoCarProposalSavePort(WebServiceFeature... features) {
        return super.getPort(NoCarProposalSavePort, NoCarProposalSave.class, features);
    }

}
